- name: Backend Setup
  hosts: all
  become: yes
  tasks:
    - name: Disable Default Nodejs Version Module
      ansible.builtin.shell: dnf disable module nodejs -y

    - name: Enable Nodejs Module for v20
      ansible.builtin.shell: dnf enable module nodejs -y

    - name: Install Nodejs
      ansible.builtin.dnf:
         name: nodejs
         state: latest

    - name: Adding Application User
      ansible.builtin.user:
        name: expense

    - name: Clean The Old Content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create App Directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download and Extract App Content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
        dest: /app
        remote_src: yes

    - name: Download Nodejs Dependencies
      community.general.npm:
        path: /app
        state: latest

    - name: Copy Backend Service File
      ansible.builtin.copy:
        name: backend.service
        dest: /etc/systemd/system/backend.service



    - name: Install Mysql Client
      ansibel.builtin.dnf:
        name: mysql
        state: latest

    - name: Load Schema
      community.mysql.mysql_db:
        name: all
        state: import
        target: /app/schema/backend.sql
        login_user: root
        login_password: ExpenseApp@1
        login_host: mysql-dev.rajdevops.online

    - name: Start Backend Service
      ansible.builtin.systemd_service:
        name: backend
        state: started
        enabled: yes
        daemon-reload: yes


#App_PreReq

#Print_Task_Heading "Start Backend Service"
#systemctl daemon-reload &>>$LOG
#systemctl enable backend &>>$LOG
#systemctl start backend &>>$LOG
#Check_Status $?


#Print_Task_Heading "Load Schema"
#mysql -h mysql-dev.rdevops6a.online -uroot -p${mysql_root_password} < /app/schema/backend.sql &>>$LOG
#Check_Status $?