- name: mysql setup
  hosts: all
  become: yes
  tasks:
    - name: Install Mysql Server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: Start Mysql Service
      ansible.builtin.systemd.service:
        name: mysqld
        state: started
        enable: yes

    - name: Setup MYsql Password
      ansible.builtin.shell: mysql_secure_installation -set-root-pass ExpenseApp@1

