- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy Expense Nginx Configuration
  ansible.builtin.copy:
    src: example.conf
    dest: /etc/nginx/default.d/example.conf

- name: Import App Pre Requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: Start Nginx
  ansible.builtin.systemd.service:
    name: nginx
    state: started
