- name: Set Prompt with component
  ansible.builtin.shell: set-prompt {{ component }}-{{ env }}


- name: Install Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter

- name: Install Logstash
  ansible.builtin.import_role:
    name: logstash

- name: Rsyslog configuration
  ansible.builtin.import_role:
    name: rsyslog
    when: rsyslog_config_needed
#3




#so from here it will go to all node_exporter